import Head from "next/head";
import { Box, Button, Heading, HStack, Img, Input, InputGroup, InputRightElement, VStack, Text, StackDivider } from "@chakra-ui/react";
import { AiFillPlusCircle } from "react-icons/ai";
import { FaTelegramPlane } from "react-icons/fa";
import { BsThreeDotsVertical } from "react-icons/bs";
import io, { Socket } from "socket.io-client";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";

interface IUserData {
  username: string;
  token: string;
}
let socket: Socket;

export default function Chat() {
  const router = useRouter();
  const selectedChat = useState(0);
  const [user, setUser] = useState<IUserData | null>(null);

  useEffect(() => {
    if (localStorage.getItem("user")) setUser(JSON.parse(localStorage.getItem("user")!));
    else router.push("/login");
    socketInitializer();
  }, []);

  async function socketInitializer() {
    socket = io("http://localhost:4040");
  }

  const handleKeypress: React.KeyboardEventHandler<HTMLInputElement> = (e) => {
    if (e.key === "Enter") {
      // send message to ws server
    }
  };

  return (
    <>
      <Head>
        <title>FaSock chat-app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HStack spacing="0" alignItems="stretch" maxH="full" h="100vh" overflow="hidden" divider={<StackDivider borderColor="#2C323D" />}>
        <VStack spacing="0" as="nav" w="md" alignItems="stretch">
          <HStack p="3" gap="1" justifyContent="space-between">
            <HStack>
              <Img src="/profile.jpg" width={45} height={45} borderRadius="full" />
              <Heading fontSize="lg">{user?.username}</Heading>
            </HStack>
            <BsThreeDotsVertical cursor="pointer" />
          </HStack>
          <Button rightIcon={<AiFillPlusCircle />} py="4" rounded="none" fontSize="lg">
            Create New Group
          </Button>
          <VStack spacing="0" divider={<StackDivider borderColor="#2C323D" />} alignItems="stretch" overflow="auto">
            <Box display="flex" alignItems="center" px="5" py="3" gap="3" _hover={{ bg: "#2c323d", borderY: "1px", borderColor: "#1a202c", cursor: "pointer" }}>
              <Img src="user.jpg" w={45} borderRadius="full" />
              <Heading fontSize="lg">First Account</Heading>
            </Box>
            <Box display="flex" alignItems="center" px="5" py="3" gap="3" _hover={{ bg: "#2c323d", borderY: "1px", borderColor: "#1a202c", cursor: "pointer" }}>
              <Img src="user.jpg" w={45} borderRadius="full" />
              <Heading fontSize="lg">Another Account</Heading>
            </Box>
            <Box display="flex" alignItems="start" justifyContent="space-between" px="5" py="3" gap="3" bg="#2b3942">
              <Img src="user.jpg" w={45} borderRadius="full" />
              <VStack flex={1} alignItems="start" spacing="0">
                <Heading fontSize="lg">Shinigami Lorem</Heading>
                <Text>Pong!</Text>
              </VStack>
              <Text alignSelf="start">10.45</Text>
            </Box>
          </VStack>
        </VStack>
        <VStack spacing="0" flexGrow={1} pb="1" alignItems="stretch">
          <HStack p="3" gap="1">
            <Img src="user.jpg" width={45} height={45} borderRadius="full" />
            <Heading fontSize="lg">Shinigami Lorem</Heading>
          </HStack>
          <VStack bg="#2C323D" flex={1} p="5" overflow="auto">
            <Text bg="ThreeDDarkShadow" rounded="md" p="2" alignSelf={"end"}>
              Ping!
            </Text>
            <Text bg="ThreeDDarkShadow" rounded="md" p="2" alignSelf={"start"}>
              Pong!
            </Text>
            <Text bg="ThreeDDarkShadow" rounded="md" p="2" alignSelf={"start"} w="45%">
              Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sint nemo illo facilis tempora labore hic beatae debitis dolor saepe explicabo in accusantium possimus, veniam inventore numquam veritatis incidunt sapiente officia?
            </Text>
            <Text bg="ThreeDDarkShadow" rounded="md" p="2" alignSelf={"end"} w="45%">
              Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sint nemo illo facilis tempora labore hic beatae debitis dolor saepe explicabo in accusantium possimus, veniam inventore numquam veritatis incidunt sapiente officia?
            </Text>
            <Text bg="ThreeDDarkShadow" rounded="md" p="2" alignSelf={"start"} w="45%">
              Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sint nemo illo facilis tempora labore hic beatae debitis dolor saepe explicabo in accusantium possimus, veniam inventore numquam veritatis incidunt sapiente officia?
            </Text>
            <Text bg="ThreeDDarkShadow" rounded="md" p="2" alignSelf={"end"} w="45%">
              Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sint nemo illo facilis tempora labore hic beatae debitis dolor saepe explicabo in accusantium possimus, veniam inventore numquam veritatis incidunt sapiente officia?
            </Text>
            <Text bg="ThreeDDarkShadow" rounded="md" p="2" alignSelf={"start"} w="45%">
              Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sint nemo illo facilis tempora labore hic beatae debitis dolor saepe explicabo in accusantium possimus, veniam inventore numquam veritatis incidunt sapiente officia?
            </Text>
            <Text bg="ThreeDDarkShadow" rounded="md" p="2" alignSelf={"end"} w="45%">
              Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sint nemo illo facilis tempora labore hic beatae debitis dolor saepe explicabo in accusantium possimus, veniam inventore numquam veritatis incidunt sapiente officia?
            </Text>
            <Text bg="ThreeDDarkShadow" rounded="md" p="2" alignSelf={"start"} w="45%">
              Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sint nemo illo facilis tempora labore hic beatae debitis dolor saepe explicabo in accusantium possimus, veniam inventore numquam veritatis incidunt sapiente officia?
            </Text>
            <Text bg="ThreeDDarkShadow" rounded="md" p="2" alignSelf={"end"} w="45%">
              Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sint nemo illo facilis tempora labore hic beatae debitis dolor saepe explicabo in accusantium possimus, veniam inventore numquam veritatis incidunt sapiente officia?
            </Text>
          </VStack>
          <InputGroup>
            <Input px="3" variant="flushed" placeholder="Enter new message..." />
            <InputRightElement cursor="pointer" children={<FaTelegramPlane />} />
          </InputGroup>
        </VStack>
        {/* <VStack flexGrow={1} pb="1" alignItems="center" justifyContent="center" direction="row">
          <Box>
            <Heading>Select chat-box to start new conversation!</Heading>
          </Box>
        </VStack> */}
      </HStack>
    </>
  );
}
