import { Button, Card, CardBody, CardHeader, Heading, Hide, HStack, Img, Link, Stack, Text, VStack } from "@chakra-ui/react";
import Head from "next/head";
import NextLink from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>FaSock chat-app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Stack p="10" gap="10">
        <HStack alignSelf="center">
          <VStack alignItems="start" maxWidth="xl">
            <Heading>Fasock chat-app</Heading>
            <Text>Simple chat-app that make easy-to-use and secure message, anywhere, with our user-friendly chat application</Text>
            <Button colorScheme="blue">
              <Link href="/login" as={NextLink} style={{ textDecoration: "none" }}>
                Try it now!
              </Link>
            </Button>
          </VStack>
          <Hide below="sm">
            <Img src="/banner.svg" width={350} height={350} />
          </Hide>
        </HStack>

        <VStack gap="10">
          <VStack>
            <Heading>Core Tech Stack</Heading>
            <HStack wrap="wrap" gap="5">
              <Card maxW="sm" align="center">
                <CardHeader pb="0.5">
                  <Img src="/next.svg" alt="NextJs logo" w="32" h="32" borderRadius="lg" />
                </CardHeader>
                <CardBody pt="0.5">
                  <Stack mt="6" spacing="3">
                    <Heading size="md">NextJs</Heading>
                    <Text>Most popular React Framework for the web, Used by some of the world's largest companies.</Text>
                  </Stack>
                </CardBody>
              </Card>
              <Card maxW="sm" align="center">
                <CardHeader pb="0.5">
                  <Img src="/fastify.svg" alt="Fastify logo" w="32" h="32" borderRadius="lg" />
                </CardHeader>
                <CardBody pt="0.5">
                  <Stack mt="6" spacing="3">
                    <Heading size="md">Fastify</Heading>
                    <Text>Fast and modern web api framework also known as beauty ecosystem.</Text>
                  </Stack>
                </CardBody>
              </Card>
              <Card maxW="sm" align="center">
                <CardHeader pb="0.5">
                  <Img src="/socket-io.svg" alt="Socket.IO logo" w="32" h="32" borderRadius="lg" />
                </CardHeader>
                <CardBody pt="0.5">
                  <Stack mt="6" spacing="3">
                    <Heading size="md">Socket.IO</Heading>
                    <Text>Bidirectional and low-latency communication for every platform.</Text>
                  </Stack>
                </CardBody>
              </Card>
            </HStack>
          </VStack>
          <VStack>
            <Heading>Data Store Stack</Heading>
            <HStack wrap="wrap" gap="5">
              <Card maxW="sm" align="center">
                <CardHeader pb="0.5">
                  <Img src="/redis.svg" alt="Redis logo" w="32" h="32" borderRadius="lg" />
                </CardHeader>
                <CardBody pt="0.5">
                  <Stack mt="6" spacing="3">
                    <Heading size="md">Redis</Heading>
                    <Text>in-memory data store used by millions of developers as a secondary database</Text>
                  </Stack>
                </CardBody>
              </Card>
              <Card maxW="sm" align="center">
                <CardHeader pb="0.5">
                  <Img src="/postgresql.svg" alt="PostgresQL logo" w="32" h="32" borderRadius="lg" />
                </CardHeader>
                <CardBody pt="0.5">
                  <Stack mt="6" spacing="3">
                    <Heading size="md">PostgresQL</Heading>
                    <Text>The World's Most Advanced Open Source Relational Database</Text>
                  </Stack>
                </CardBody>
              </Card>
              <Card maxW="sm" align="center">
                <CardHeader pb="0.5">
                  <Img src="/typeorm.svg" alt="TypeORM logo" w="32" h="32" borderRadius="lg" />
                </CardHeader>
                <CardBody pt="0.5">
                  <Stack mt="6" spacing="3">
                    <Heading size="md">TypeORM</Heading>
                    <Text>Best lightweight Object Relational Mapping for Node.js application.</Text>
                  </Stack>
                </CardBody>
              </Card>
            </HStack>
          </VStack>
        </VStack>
      </Stack>
    </>
  );
}
